import { ShippingLineRules } from "@/types";

export const DEFAULT_SHIPPING_RULES: ShippingLineRules[] = [
  {
    id: "1",
    line_name: "Maersk",
    line_code: "MAEU",
    port: "Kandla/Mundra",
    container_type: "20ft",
    model: "split",
    dem_free_days: 14,
    det_free_days: 7,
    slab1_days: 7,
    slab1_rate: 1800,
    slab2_days: 7,
    slab2_rate: 3200,
    slab3_rate: 5500,
    calendar_basis: "calendar",
    is_custom: false,
    created_at: new Date().toISOString(),
  },
  {
    id: "2",
    line_name: "MSC",
    line_code: "MEDU",
    port: "Kandla/Mundra",
    container_type: "20ft",
    model: "split",
    dem_free_days: 10,
    det_free_days: 7,
    slab1_days: 5,
    slab1_rate: 2200,
    slab2_days: 7,
    slab2_rate: 3800,
    slab3_rate: 6000,
    calendar_basis: "calendar",
    is_custom: false,
    created_at: new Date().toISOString(),
  },
  {
    id: "3",
    line_name: "COSCO",
    line_code: "COSU",
    port: "Kandla/Mundra",
    container_type: "20ft",
    model: "split",
    dem_free_days: 14,
    det_free_days: 7,
    slab1_days: 7,
    slab1_rate: 1600,
    slab2_days: 7,
    slab2_rate: 2900,
    slab3_rate: 5000,
    calendar_basis: "calendar",
    is_custom: false,
    created_at: new Date().toISOString(),
  },
  {
    id: "4",
    line_name: "ONE",
    line_code: "ONEY",
    port: "Kandla/Mundra",
    container_type: "20ft",
    model: "split",
    dem_free_days: 12,
    det_free_days: 7,
    slab1_days: 7,
    slab1_rate: 1700,
    slab2_days: 7,
    slab2_rate: 3000,
    slab3_rate: 5200,
    calendar_basis: "calendar",
    is_custom: false,
    created_at: new Date().toISOString(),
  },
];

export function getRulesForLine(lineName: string): ShippingLineRules | undefined {
  return DEFAULT_SHIPPING_RULES.find(
    (rule) => rule.line_name.toLowerCase() === lineName.toLowerCase()
  );
}
